/**
 * Short reminder-text-style definitions for common keyword abilities.
 * Scryfall's card data lists keyword names but not their rules text, so this
 * is what powers the inspector's hover tooltips. Not exhaustive — obscure or
 * one-off set-specific keywords just won't have a tooltip.
 */
export const KEYWORD_GLOSSARY: Record<string, string> = {
  flying: "Can only be blocked by creatures with flying or reach.",
  reach: "Can block creatures with flying.",
  trample: "Excess combat damage beyond what's needed to destroy the blocker carries over to the defending player.",
  "first strike": "Deals combat damage before creatures without first strike.",
  "double strike": "Deals combat damage in both the first-strike and regular damage steps.",
  deathtouch: "Any amount of combat damage it deals to a creature is enough to destroy it.",
  defender: "Can't attack.",
  flash: "Can be cast any time you could cast an instant.",
  haste: "Can attack and tap the turn it comes under your control.",
  hexproof: "Can't be the target of spells or abilities your opponents control.",
  indestructible: "Can't be destroyed by damage or by effects that say 'destroy'.",
  lifelink: "Damage it deals also causes you to gain that much life.",
  menace: "Can't be blocked except by two or more creatures.",
  vigilance: "Attacking doesn't cause it to tap.",
  ward: "Whenever it becomes the target of a spell or ability an opponent controls, that opponent pays a cost or the spell/ability is countered.",
  protection: "Can't be blocked, targeted, dealt damage, enchanted, or equipped by the stated quality.",
  prowess: "Whenever you cast a noncreature spell, gets +1/+1 until end of turn.",
  cascade: "When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less, then you may cast it for free.",
  convoke: "Your creatures can help cast this spell — each creature you tap while casting pays for {1} or one mana of that creature's color.",
  delve: "Each card you exile from your graveyard while casting this spell pays for {1}.",
  escape: "Can be cast from your graveyard by paying its escape cost and exiling other cards from your graveyard.",
  flashback: "Can be cast from your graveyard for its flashback cost, then exiled.",
  kicker: "May be cast for an additional cost for a bonus effect.",
  landfall: "Triggers whenever a land enters the battlefield under your control.",
  mentor: "Whenever it attacks, put a +1/+1 counter on target attacking creature with lesser power.",
  scry: "Look at that many cards from the top of your library, then put any number of them on the bottom and the rest back on top in any order.",
  surveil: "Look at that many cards from the top of your library, then put any number of them into your graveyard and the rest back on top in any order.",
  adventure: "Can be cast as an instant/sorcery Adventure first, then cast later as the creature from exile.",
  afterlife: "When it dies, create that many 1/1 white and black Spirit creature tokens with flying.",
  annihilator: "Whenever it attacks, defending player sacrifices that many permanents.",
  bestow: "Can be cast as an Aura for its bestow cost; if the enchanted permanent leaves, it becomes a creature.",
  bloodthirst: "Enters with additional +1/+1 counters if an opponent was dealt damage this turn.",
  changeling: "Is every creature type at all times.",
  channel: "Can be discarded from your hand for its channel cost to produce an effect.",
  cipher: "May be exiled encoded on a creature you control; whenever that creature deals combat damage, you may cast a copy of this spell.",
  cleave: "Can be cast for its cleave cost, removing the bracketed text.",
  conspire: "Cast this by also tapping two untapped creatures sharing a color with it, to copy it.",
  crew: "Tap any number of creatures you control with total power N or more to turn this Vehicle into a creature until end of turn.",
  cycling: "May be discarded for its cycling cost to draw a card.",
  dash: "May be cast for its dash cost; it gains haste and returns to your hand at end of turn.",
  devoid: "Has no color.",
  disturb: "Can be cast from your graveyard transformed, for its disturb cost.",
  dredge: "Instead of drawing a card, you may mill that many cards to return this from your graveyard to your hand.",
  echo: "At the beginning of your upkeep after this came under your control, you may pay its echo cost; otherwise, sacrifice it.",
  embalm: "May exile this from your graveyard, paying its embalm cost, to create a token copy of it (as a white Zombie with no mana cost).",
  emerge: "May be cast by sacrificing a creature and paying the emerge cost reduced by that creature's mana value.",
  enrage: "Triggers whenever this creature is dealt damage.",
  entwine: "Pay the entwine cost to choose all modes of this spell instead of just one.",
  eternalize: "May exile this from your graveyard, paying its eternalize cost, to create a token copy at 4/4 (as a black Zombie).",
  evoke: "May be cast for its evoke cost; if you do, sacrifice it when it enters.",
  exalted: "Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
  exploit: "When it enters, you may sacrifice a creature.",
  extort: "Whenever you cast a spell, you may pay {W/B}; if you do, each opponent loses 1 life and you gain that much life.",
  fabricate: "When it enters, put that many +1/+1 counters on it, or create that many 1/1 Servo tokens.",
  flanking: "Whenever it becomes blocked by a creature without flanking, that creature gets -1/-1 until end of turn.",
  fuse: "If this is a split card, you may cast both halves at once by paying both costs.",
  horsemanship: "Can only be blocked by creatures with horsemanship.",
  infect: "Deals damage to creatures in the form of -1/-1 counters and to players in the form of poison counters.",
  intimidate: "Can only be blocked by artifact creatures and creatures sharing a color with it.",
  "living weapon": "When this Equipment enters, create a 0/0 black Germ creature token and attach this to it.",
  madness: "If discarded, you may cast it for its madness cost instead of putting it in your graveyard.",
  megamorph: "Can be cast face down as a 2/2, then turned face up for its megamorph cost, adding a +1/+1 counter.",
  miracle: "May be cast for its miracle cost when it's the first card you draw this turn.",
  morph: "Can be cast face down as a 2/2 for {3}, then turned face up by paying its morph cost.",
  mutate: "May be cast targeting a non-Human creature you own or control, merging with it into one creature.",
  outlast: "May tap to put a +1/+1 counter on this creature; doing so doesn't cause it to tap for other purposes if it's already tapped, and it can't attack that turn.",
  overload: "May be cast for its overload cost to apply its effect to every eligible permanent instead of one target.",
  persist: "When it dies, if it had no -1/-1 counters on it, return it to the battlefield with a -1/-1 counter.",
  phasing: "Phases in and out of existence, alternating each of its controller's untap steps.",
  "proliferate": "Choose any number of permanents and/or players with a counter, then give each one more of each kind of counter already there.",
  provoke: "You may have target creature block it, and that creature is removed from combat if unable.",
  raid: "Triggers if you attacked with a creature this turn.",
  rampage: "Gets +N/+N for each creature blocking it beyond the first.",
  reconfigure: "Can attach to a creature as an Equipment for its reconfigure cost, or unattach to become a creature again.",
  regenerate: "The next time it would be destroyed this turn, it isn't; instead tap it, remove it from combat, and heal all damage.",
  renown: "The first time it deals combat damage to a player, put that many +1/+1 counters on it and it becomes renowned.",
  replicate: "Pay its replicate cost any number of times when casting to create that many copies.",
  retrace: "May be cast from your graveyard by discarding a land in addition to its other costs.",
  riot: "Enters with your choice of a +1/+1 counter or haste.",
  scavenge: "May exile this card from your graveyard, paying its scavenge cost, to put that many +1/+1 counters on target creature.",
  shadow: "Can only block or be blocked by creatures with shadow.",
  shroud: "Can't be the target of any spells or abilities.",
  soulbond: "May pair with another unpaired creature as they enter or become unpaired, granting a shared bonus.",
  splice: "May reveal this card from your hand while casting another spell of the named type, adding this card's effects for its splice cost.",
  "split second": "While on the stack, players can't cast spells or activate abilities that aren't mana abilities.",
  storm: "When you cast this spell, copy it for each spell cast before it this turn.",
  sunburst: "Enters with a counter for each color of mana spent to cast it.",
  suspend: "May be cast by exiling it with time counters for its suspend cost, removing one each upkeep; when the last is removed, it's cast for free (or comes into play if a permanent).",
  transfigure: "May sacrifice a creature and pay its transfigure cost to search your library for a creature card and put it onto the battlefield.",
  transmute: "May discard this card and pay its transmute cost to search your library for a card with the same mana value and put it into your hand.",
  tribute: "As it enters, an opponent chooses to give it a bonus or trigger an alternate effect.",
  undying: "When it dies, if it had no +1/+1 counters on it, return it to the battlefield with a +1/+1 counter.",
  unearth: "May be cast from your graveyard for its unearth cost; it gains haste and is exiled if it would leave the battlefield or at end of turn.",
  unleash: "May enter with a +1/+1 counter; if it does, it can't block.",
  wither: "Deals damage to creatures in the form of -1/-1 counters instead of normal damage.",
};

export function keywordTooltip(keyword: string): string | undefined {
  return KEYWORD_GLOSSARY[keyword.toLowerCase().trim()];
}
